{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sample-lib-nodejs/1.0/sample-lib-nodejs-1.0.module",
    "group": "com.example",
    "module": "sample-lib-nodejs",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "zm44uqhl3ve5rk7er23d2uca5e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-dev-3635"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-metadata-1.0.jar",
          "url": "sample-lib-metadata-1.0.jar",
          "size": 1039,
          "sha512": "36a224c66beaed078d51bc170f3fecd8df3ec53891a3affd13b9b709d575650ce9a5e6c109ae7f7572f6d2dcda168d7425b0593bab0866459939c729df49f188",
          "sha256": "92139313ed7ef5fc274d17c31accb1878c91ce5216837d344cd3b5bb4bf73038",
          "sha1": "3a82815c24ada77a4dee0f0780a06074d0fd2a1b",
          "md5": "0f60ed428ca4f7210edb640dd7d8d3e5"
        }
      ]
    }
  ]
}
