{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sample-lib/1.0/sample-lib-1.0.module",
    "group": "com.example",
    "module": "sample-lib",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "zm44uqhl3ve5rk7er23d2uca5e"
    }
  },
  "variants": [
    {
      "name": "nodeJsLegacy-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0-dev-3635"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-dev-3635"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-nodejslegacy-1.0.jar",
          "url": "sample-lib-nodejs-1.0.jar",
          "size": 2668,
          "sha512": "eae59179d72ee3b1793c8646c1adb1540738c02b32c2a1f429fcc104785b0ec400c6512258c358ddce0e0213d1a96543eafac0a123a9d6f232f098794fa2699b",
          "sha256": "3458b7657345ddbb7ed7ec61a4aa460a3c0c40da0c7ee1b89476ced1718a71b1",
          "sha1": "cb4ac43305b342dee1c5c701c82f84e1aad83524",
          "md5": "15cadc966cb1002abcdf0c6a87bec2db"
        }
      ]
    },
    {
      "name": "nodeJsLegacy-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0-dev-3635"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-dev-3635"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-nodejslegacy-1.0.jar",
          "url": "sample-lib-nodejs-1.0.jar",
          "size": 2668,
          "sha512": "eae59179d72ee3b1793c8646c1adb1540738c02b32c2a1f429fcc104785b0ec400c6512258c358ddce0e0213d1a96543eafac0a123a9d6f232f098794fa2699b",
          "sha256": "3458b7657345ddbb7ed7ec61a4aa460a3c0c40da0c7ee1b89476ced1718a71b1",
          "sha1": "cb4ac43305b342dee1c5c701c82f84e1aad83524",
          "md5": "15cadc966cb1002abcdf0c6a87bec2db"
        }
      ]
    },
    {
      "name": "nodeJsIr-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0-dev-3635"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-dev-3635"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-nodejsir-1.0.klib",
          "url": "sample-lib-nodejs-1.0.klib",
          "size": 3640,
          "sha512": "7ba950533700c1b406aeb3e22cbd09ce305186b58efb87037d6505cbc12ddae3e7ec97d5fcf0ca2b89774b2c0970642a652d2e16565677753a55a92539f0fd35",
          "sha256": "f18ea24f6087a0d23b599bd80823a85656546dccb96f8cc26d8549c2c1a5ad34",
          "sha1": "dcc4fd95a97d772520cc9d9edb735e980057f733",
          "md5": "57e45a66682b7ec8aa78641da2836130"
        }
      ]
    },
    {
      "name": "nodeJsIr-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0-dev-3635"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-dev-3635"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-nodejsir-1.0.klib",
          "url": "sample-lib-nodejs-1.0.klib",
          "size": 3640,
          "sha512": "7ba950533700c1b406aeb3e22cbd09ce305186b58efb87037d6505cbc12ddae3e7ec97d5fcf0ca2b89774b2c0970642a652d2e16565677753a55a92539f0fd35",
          "sha256": "f18ea24f6087a0d23b599bd80823a85656546dccb96f8cc26d8549c2c1a5ad34",
          "sha1": "dcc4fd95a97d772520cc9d9edb735e980057f733",
          "md5": "57e45a66682b7ec8aa78641da2836130"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../sample-lib-metadata/1.0/sample-lib-metadata-1.0.module",
        "group": "com.example",
        "module": "sample-lib-metadata",
        "version": "1.0"
      }
    }
  ]
}
