{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sample-lib/1.0/sample-lib-1.0.module",
    "group": "com.example",
    "module": "sample-lib",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "cl5mr5atjrfkpjp44phfe6nieq"
    }
  },
  "variants": [
    {
      "name": "nodeJs-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4-M1-eap-61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4-M1-eap-61"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-legacynodejs-1.0.jar",
          "url": "sample-lib-nodejs-1.0.jar",
          "size": 2668,
          "sha512": "c7d078f9157a429f8319bd6177be136d38b7c46cb2f5063c48659a63c14eea513ddc1edea309b1ab1c4cafcdf23faddeeadde922f7cf85cf5d4f7abf26ef019c",
          "sha256": "098e862c7220b1f83fcc45cc01031109e9169810b7410b47d3485a4ca635d405",
          "sha1": "754a696c6a0c16146e988e7478bb38e1dc554a02",
          "md5": "72f041fb7eb5953481c7c8154ce7fd72"
        }
      ]
    },
    {
      "name": "nodeJs-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4-M1-eap-61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4-M1-eap-61"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-legacynodejs-1.0.jar",
          "url": "sample-lib-nodejs-1.0.jar",
          "size": 2668,
          "sha512": "c7d078f9157a429f8319bd6177be136d38b7c46cb2f5063c48659a63c14eea513ddc1edea309b1ab1c4cafcdf23faddeeadde922f7cf85cf5d4f7abf26ef019c",
          "sha256": "098e862c7220b1f83fcc45cc01031109e9169810b7410b47d3485a4ca635d405",
          "sha1": "754a696c6a0c16146e988e7478bb38e1dc554a02",
          "md5": "72f041fb7eb5953481c7c8154ce7fd72"
        }
      ]
    },
    {
      "name": "nodeJsIr-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4-M1-eap-61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4-M1-eap-61"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-nodejsir-1.0.klib",
          "url": "sample-lib-nodejs-1.0.klib",
          "size": 3640,
          "sha512": "6d2d13bf4f819e98f96fc5e9e5a84c58d198e52d7160774f7d6b96c353d7e4f143bef1c4afde709f9fa5ea8bfc65131e6e4477930a81c7fafbb8f3f9a15910a6",
          "sha256": "3c243d6d28e525addca9bd4944ac0fd3fd7ce9736594a030ecf4917f70b41ba9",
          "sha1": "8627bbefe503482d86e8d8d452387a1d42b19c6c",
          "md5": "d1c30c877109c343ac310084c12af488"
        }
      ]
    },
    {
      "name": "nodeJsIr-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4-M1-eap-61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4-M1-eap-61"
          }
        }
      ],
      "files": [
        {
          "name": "sample-lib-nodejsir-1.0.klib",
          "url": "sample-lib-nodejs-1.0.klib",
          "size": 3640,
          "sha512": "6d2d13bf4f819e98f96fc5e9e5a84c58d198e52d7160774f7d6b96c353d7e4f143bef1c4afde709f9fa5ea8bfc65131e6e4477930a81c7fafbb8f3f9a15910a6",
          "sha256": "3c243d6d28e525addca9bd4944ac0fd3fd7ce9736594a030ecf4917f70b41ba9",
          "sha1": "8627bbefe503482d86e8d8d452387a1d42b19c6c",
          "md5": "d1c30c877109c343ac310084c12af488"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../sample-lib-metadata/1.0/sample-lib-metadata-1.0.module",
        "group": "com.example",
        "module": "sample-lib-metadata",
        "version": "1.0"
      }
    }
  ]
}
