{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "sample-lib",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "zm44uqhl3ve5rk7er23d2uca5e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../sample-lib-metadata/1.0/sample-lib-metadata-1.0.module",
        "group": "com.example",
        "module": "sample-lib-metadata",
        "version": "1.0"
      }
    },
    {
      "name": "nodeJsLegacy-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../sample-lib-nodejs/1.0/sample-lib-nodejs-1.0.module",
        "group": "com.example",
        "module": "sample-lib-nodejs",
        "version": "1.0"
      }
    },
    {
      "name": "nodeJsLegacy-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../sample-lib-nodejs/1.0/sample-lib-nodejs-1.0.module",
        "group": "com.example",
        "module": "sample-lib-nodejs",
        "version": "1.0"
      }
    },
    {
      "name": "nodeJsIr-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../sample-lib-nodejs/1.0/sample-lib-nodejs-1.0.module",
        "group": "com.example",
        "module": "sample-lib-nodejs",
        "version": "1.0"
      }
    },
    {
      "name": "nodeJsIr-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../sample-lib-nodejs/1.0/sample-lib-nodejs-1.0.module",
        "group": "com.example",
        "module": "sample-lib-nodejs",
        "version": "1.0"
      }
    }
  ]
}
